[build]
  functions = "functions"

[dev]
  functions = "functions"
  publish = "BC COIA calculator"
  port = 8888

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

# Handle test mode path
[[redirects]]
  from = "/test"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/test/*"
  to = "/index.html"
  status = 200
